name: Increment value in theme.conf.php

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'sbpp-windmill-dashboard/theme.conf.php'
 
jobs:
  test:
    name: Increment value in theme.conf.php
    runs-on: ubuntu-latest

    steps:
      - name: Increment patch version
        uses: yoichiro/gh-action-increment-value@v5
        with:
          token: ${{ secrets.PAT }}
          target_directory: 'sbpp-windmill-dashboard'
          target_file: 'theme.conf.php'
          prefix: 'define(''theme_version'', "0.0.'
          suffix: '");'
          commit_message: '[skip ci] Increments the theme version to 0.0.'
