name: Zip and Attach to Release

on:
  workflow_dispatch: # Trigger manually
  release:
    types: [published] # Trigger when a release is published

jobs:
  zip-and-attach:
    name: Zip and Attach Repository Content
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Get the release tag
      - name: Extract Release Tag
        run: echo "RELEASE_TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

      # Step 3: Zip the repository content with the tag in the file name
      - name: Create ZIP Archive
        run: |
          zip -r SBPP-Windmill-Dashboard-${RELEASE_TAG}.zip .

      # Step 4: Upload the ZIP file as an asset to the release
      - name: Upload ZIP to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: SBPP-Windmill-Dashboard-${{ env.RELEASE_TAG }}.zip
          asset_name: SBPP-Windmill-Dashboard-${{ env.RELEASE_TAG }}.zip
          asset_content_type: application/zip
